POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Michael",
    "number": "999-123456"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Michael"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "999-123456"
}